### ISSUE TITLE
Non canonical amino acids

### ISSUE THREAD

**Issue by jnoske** [xiaoqiah/EvoEF#4]
Hi,

Thanks for the excellent work. I was wondering whether it would be possible to support non-canonical amino acids in EvoEF such as phosphoserine.

Thanks a lot.

**Comment by tommyhuangthu** [comment]
Thanks for your interest. Unfortunately, so far not. Maybe you can check if FoldX or Rosetta support PTM residues.

Best wishes,
Xiaoqiang

From: Jakob Noske ***@***.***>
Sent: Thursday, September 28, 2023 04:30
To: tommyhuangthu/EvoEF ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [tommyhuangthu/EvoEF] Non canonical amino acids (Issue #4)


Hi,

Thanks for the excellent work. I was wondering whether it would be possible to support non-canonical amino acids in EvoEF such as phosphoserine.

Thanks a lot.

**Comment by jnoske** [comment]
Hi,

Thanks for the quick reply. Yes I will have a look at these tools then.
