### ISSUE TITLE
Rotamer library

### ISSUE THREAD

**Issue by jnoske** [xiaoqiah/EvoEF#5]
Is it possible to use a library with more rotamere and does this make the algorithm more accurate?

**Comment by tommyhuangthu** [comment]
Yes, I think so. There are four rotamer libraries in the EvoEF/library directory: rotlib984.txt, rotlib3222.txt, rotlib7421.txt, and rotlib11810.txt. By default, rotlib984 is used with a balanced accuracy and running speed. You can change the code in EvoEF/src/Main.cpp on line 76: change the rotamer library to the one you want to use, save the file, and recompile the code the generate the EvoEF executable.

Best wishes,
Xiaoqiang
________________________________
From: Jakob Noske ***@***.***>
Sent: Thursday, March 21, 2024 15:01
To: tommyhuangthu/EvoEF ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [tommyhuangthu/EvoEF] Rotamer library (Issue #5)


Is it possible to use a library with more rotamere and does this make the algorithm more accurate?

**Comment by jnoske** [comment]
Thank you for the help! Is there any information how these different sizes of rotamer libraries where compiled?

**Comment by tommyhuangthu** [comment]
Hello, You can refer to this paper for information on the rotamer library: https://doi.org/10.1006/jmbi.2001.4865

Best wishes,
Xiaoqiang

________________________________

**Comment by jnoske** [comment]
Thank you!
